[general]
project_id = "lnpkzwholfxycuapezke"

[api]
enabled_schemas = ["public", "auth"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
auto_confirm_new_users = true

[local]
api_url = "http://localhost:54321"
db_url = "postgresql://postgres:postgres@localhost:54322/postgres"